# Generating Data w/ Numpy

In [2]:
import numpy as np

### np.empty(), np.zeros(), np.ones(), np.full()

In [6]:
# creates an empty array of a defined shape with empty values. This is the fastest way to create an nd array
array_empty = np.empty(shape = (2,3))
array_empty

array([[1.79769313e+308, 1.79769313e+308, 2.00000000e+000],
       [2.22044605e-016, 2.22507386e-308, 4.94065646e-324]])

In [8]:
# creates an empty array of a defined shape with empty values. The advantage over np.empty() is that values are always 
# 0 rather than some random tiny numbers

array_0s = np.zeros(shape = (2,3))
array_0s

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
# creating an empty nd array using np.zeros but with a defined datatype

array_0s = np.zeros(shape = (2,3), dtype = np.int8)
array_0s

array([[0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [11]:
# works just like np.zeros but with 1ss instead of zeros

array_1s = np.ones(shape = (2,3))
array_1s

array([[1., 1., 1.],
       [1., 1., 1.]])

In [13]:
# works like the other empty array values except that the fill_value parameter is required
# fill_value values can be other data types like string too

array_full = np.full(shape = (2,3), fill_value = 2)
array_full

array([[2, 2, 2],
       [2, 2, 2]])

### "_like" functions

In [3]:
matrix_A = np.array([[1,0,9,2,2],[3,23,4,5,1],[0,2,3,4,1]])
matrix_A

array([[ 1,  0,  9,  2,  2],
       [ 3, 23,  4,  5,  1],
       [ 0,  2,  3,  4,  1]])

In [5]:
# like functions are equvilent to the previous functions where the definition of the shape is based on another existing matrix
array_empty_like = np.empty_like(matrix_A)
array_empty_like

array([[      0,       0,       0,       0,       0],
       [      0,       0,       0,       0,       0],
       [      0,       0,       0,       0, 7929968]])

In [6]:
# here we copy the shape of another matrix but fill it with 0s instead of the random values in the empty_like function
array_0s_like = np.zeros_like(matrix_A)
array_0s_like

# applications:
# can be used as a form of switch based on another array of the same shape

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

### np.arange()

In [7]:
# generate a sequence of numbers within a range as a list
list(range(30))

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29]

In [8]:
# generate a sequence of numbers within a range as an array
array_rng = np.arange(30)
array_rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [10]:
# generate a sequence of numbers within a range as an array (with useful arguments)
array_rng = np.arange(stop = 30)
array_rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [11]:
# generate a sequence of numbers within a range as an array (with useful arguments)
array_rng = np.arange(start = 0, stop = 30)
array_rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [12]:
# generate a sequence of numbers within a range as an array (with useful arguments)
array_rng = np.arange(start = 0, stop = 30, step = 2.5)
array_rng

array([ 0. ,  2.5,  5. ,  7.5, 10. , 12.5, 15. , 17.5, 20. , 22.5, 25. ,
       27.5])

In [15]:
# generate a sequence of numbers within a range as an array (with useful arguments)
array_rng = np.arange(start = 0, stop = 30, step = 2.5, dtype = np.float64)
array_rng

array([ 0. ,  2.5,  5. ,  7.5, 10. , 12.5, 15. , 17.5, 20. , 22.5, 25. ,
       27.5])

## Random Generators

### Defining Random Generators

In [2]:
from numpy.random import Generator as gen # the Generator function takes a bit generator as an input and creates generator objects
from numpy.random import PCG64 as pcg # Permutation Congruential Generator

In [3]:
array_RG = gen(pcg())
array_RG.normal() # random numbers from a normal distribution

1.0721008295245222

In [4]:
# the size argument allows us to specify how many random values we wish to generate
array_RG = gen(pcg())
array_RG.normal(size = 5)
# this is a 1-d nd array

array([ 0.80636912,  0.18834681, -0.08694672,  1.76292691,  1.73094455])

In [5]:
# the size argument allows us to specify how many random values we wish to generate
array_RG = gen(pcg())
array_RG.normal(size = (5,5))
# this is a 5x5 nd array specified inside the tuple

array([[-0.3390424 ,  0.01082589,  0.49992466, -1.21375835, -0.80443943],
       [-0.13695266, -0.24216411, -1.72166559, -1.05236999, -0.65266915],
       [-0.79732986, -0.69148482,  0.15718444,  0.27182129,  1.77656156],
       [-1.23428869, -0.51803314,  0.85654137, -0.01250446,  0.02265411],
       [ 1.4729572 ,  0.6462326 , -1.07240196,  1.21684377, -1.84843711]])

### Generating Integers, Probabilities and Random Choices

In [7]:
# the size argument allows us to specify how many random values we wish to generate
# to keep consistant random numbers specify a seed value which would give the same random numbers on every generation
array_RG = gen(pcg(seed = 365))
array_RG.normal(size = (5,5))


array([[-0.13640899,  0.09414431, -0.06300442,  1.05391641, -0.6866818 ],
       [-0.50922173, -0.7999526 ,  0.73041825,  0.08825439, -2.1177576 ],
       [ 0.65526774, -0.48095012, -0.5519114 , -0.58578662, -0.98257896],
       [ 1.12378166, -1.30984316, -0.04703774,  0.955272  ,  0.26071745],
       [-0.20023668, -1.50172484, -1.4929163 ,  0.96535084,  1.18694633]])

In [8]:
# generate random integers between 0 and 10 of 5x5 nd arrays
array_RG = gen(pcg(seed = 365))
array_RG.integers(10, size = (5,5))

array([[0, 7, 6, 7, 8],
       [6, 6, 2, 0, 6],
       [3, 0, 3, 7, 9],
       [1, 1, 8, 7, 4],
       [4, 8, 6, 4, 9]])

In [9]:
#...or specify upper and lower limits
array_RG = gen(pcg(seed = 365))
array_RG.integers(low = 10, high = 100, size = (5,5))

array([[18, 78, 64, 78, 84],
       [66, 67, 28, 10, 69],
       [45, 15, 37, 74, 96],
       [19, 21, 89, 73, 54],
       [53, 84, 66, 51, 92]])

In [10]:
# generating random probability values (from a continous uniform distribution)
array_RG = gen(pcg(seed = 365))
array_RG.random(size = (5,5))

array([[0.75915734, 0.7662218 , 0.6291028 , 0.20336599, 0.66501486],
       [0.06559111, 0.71326309, 0.10812106, 0.87969046, 0.49405844],
       [0.82472673, 0.45652944, 0.07367232, 0.69628564, 0.36690736],
       [0.29787156, 0.4996155 , 0.4865245 , 0.62740703, 0.54952637],
       [0.64894629, 0.04411757, 0.7206516 , 0.84594003, 0.17159792]])

In [12]:
# generating random probability values (from a range of numbers from ones choice)
# this method defaults to a unform distribution i.e. each element has an equal probability of being selected
array_RG = gen(pcg(seed = 365))
array_RG.choice([1,2,3,4,5], size = (5,5))

array([[1, 4, 4, 4, 5],
       [4, 4, 2, 1, 4],
       [2, 1, 2, 4, 5],
       [1, 1, 5, 4, 3],
       [3, 5, 4, 3, 5]])

In [13]:
# generating random probability values (from a range of numbers from ones choice)
# this method defaults to a unform distribution i.e. each element has an equal probability of being selected
# however, using the p argument, the probability for each element can be inputted
array_RG = gen(pcg(seed = 365))
array_RG.choice([1,2,3,4,5], p = [0.1,0.1,0.1,0.1,0.6], size = (5,5))

array([[5, 5, 5, 3, 5],
       [1, 5, 2, 5, 5],
       [5, 5, 1, 5, 4],
       [3, 5, 5, 5, 5],
       [5, 1, 5, 5, 2]])

### Generating Arrays From Known Distributions

https://numpy.org/doc/stable/reference/random/generator

### Applications of Random Generators