# Generating Data w/ Numpy

In [2]:
import numpy as np

### np.empty(), np.zeros(), np.ones(), np.full()

In [6]:
# creates an empty array of a defined shape with empty values. This is the fastest way to create an nd array
array_empty = np.empty(shape = (2,3))
array_empty

array([[1.79769313e+308, 1.79769313e+308, 2.00000000e+000],
       [2.22044605e-016, 2.22507386e-308, 4.94065646e-324]])

In [8]:
# creates an empty array of a defined shape with empty values. The advantage over np.empty() is that values are always 
# 0 rather than some random tiny numbers

array_0s = np.zeros(shape = (2,3))
array_0s

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
# creating an empty nd array using np.zeros but with a defined datatype

array_0s = np.zeros(shape = (2,3), dtype = np.int8)
array_0s

array([[0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [11]:
# works just like np.zeros but with 1ss instead of zeros

array_1s = np.ones(shape = (2,3))
array_1s

array([[1., 1., 1.],
       [1., 1., 1.]])

In [13]:
# works like the other empty array values except that the fill_value parameter is required
# fill_value values can be other data types like string too

array_full = np.full(shape = (2,3), fill_value = 2)
array_full

array([[2, 2, 2],
       [2, 2, 2]])

### "_like" functions

### np.arange()

## Random Generators

### Defining Random Generators

### Generating Integers, Probabilities and Random Choices

### Generating Arrays From Known Distributions

https://numpy.org/doc/stable/reference/random/generator

### Applications of Random Generators