# Working with Arrays

In [2]:
import numpy as np

## Slicing

In [3]:
matrix_A = np.array([[1,2,3],[4,5,6]])
matrix_A

array([[1, 2, 3],
       [4, 5, 6]])

### Basic Slicing

In [4]:
matrix_A[:] # default slicing returns the exact same matrix back because no before or after rows have been specified

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
matrix_A[0:0] # returns an empty matrix because there are no rows the first one and itself

array([], shape=(0, 3), dtype=int64)

In [6]:
matrix_A[0:1] # returns the rows between the first row and the second row i.e. the first row

# note: indexing in numpy is closed-open meaning the upper limit is not included when slicing

array([[1, 2, 3]])

In [7]:
matrix_A[1:] # take from the second row onwards

array([[4, 5, 6]])

In [8]:
matrix_A[:2] # take upto the second row

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
matrix_A[0] # produces a 1-d slice

array([1, 2, 3])

In [10]:
matrix_A[:1] # same putput but produces a 2-d slice

array([[1, 2, 3]])

In [11]:
matrix_A[:-1] # the use of negative values e.g. taking the element prior to the last value

array([[1, 2, 3]])

In [12]:
matrix_A[:,1:] # slicing columns, to the left of the comma are the rows and to the right of the comma are the columns

# this example takes all rows but then slices from the second column onwards

array([[2, 3],
       [5, 6]])

In [13]:
matrix_A[1:,1:] # slice from second column and second row onwards

array([[5, 6]])

### Stepwise Slicing

In [14]:
matrix_B = np.array([[1,1,1,2,0],[3,6,6,7,4],[4,5,3,8,0]])
matrix_B

array([[1, 1, 1, 2, 0],
       [3, 6, 6, 7, 4],
       [4, 5, 3, 8, 0]])

In [15]:
# slicing works by: first colon separates the row and column and the second colon separates the step.
# e.g. the below matrix takes all rows and columns but skips every other row
matrix_B[::2,::]

array([[1, 1, 1, 2, 0],
       [4, 5, 3, 8, 0]])

In [16]:
# slicing works by: first colon separates the row and column and the second colon separates the step.
# e.g. the below matrix takes all rows and columns but skips every other column
matrix_B[::,::2]

array([[1, 1, 0],
       [3, 6, 4],
       [4, 3, 0]])

In [17]:
# slicing works by: first colon separates the row and column and the second colon separates the step.
# e.g. the below matrix takes all rows and columns but skips every other row and every other column
matrix_B[::2,::2]

array([[1, 1, 0],
       [4, 3, 0]])

In [18]:
# dealing with negative steps; skips rows and/or columns but works backwards as can be seen below
# slicing works by: first colon separates the row and column and the second colon separates the step.
# e.g. the below matrix takes all rows and columns but skips every other row and every other column
matrix_B[::-2,::2]

array([[4, 3, 0],
       [1, 1, 0]])

### Conditional Slicing

In [19]:
matrix_c = np.array([[1,1,1,2,0],[3,6,6,7,4],[4,5,3,8,0]])
matrix_c

array([[1, 1, 1, 2, 0],
       [3, 6, 6, 7, 4],
       [4, 5, 3, 8, 0]])

In [20]:
matrix_c[:,0] # slice only all the rows but only the first column

array([1, 3, 4])

In [21]:
matrix_c[:,0] > 2 # applying conditions to the array elements

array([False,  True,  True])

In [22]:
matrix_c[:,:] > 2 # apply the condition to the entire array i.e. all rows and all columns

array([[False, False, False, False, False],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False]])

In [23]:
matrix_c[matrix_c[:,:] > 2] # displaying the values that meet the conditions instead of True or False
# since NumPy doesn't know how many elements would fit the condition it outputs a 1-D array instead

array([3, 6, 6, 7, 4, 4, 5, 3, 8])

In [24]:
# multiple conditions can also be applied to filtering an n-d array
matrix_c[(matrix_c[:,:] % 2 == 0) & (matrix_c[:,:] <= 4)]
# this condition filters the matrix for even numbers AND which are equal to or less than 4

array([2, 0, 4, 4, 0])

In [25]:
# multiple conditions can also be applied to filtering an n-d array
matrix_c[(matrix_c[:,:] % 2 == 0) | (matrix_c[:,:] <= 4)]
# this condition filters the matrix for even numbers OR that are equal to or less than 4

array([1, 1, 1, 2, 0, 3, 6, 6, 4, 4, 3, 8, 0])

## Dimensions and the Squeeze Function

In [26]:
matrix_D = np.array([[1,1,1,2,0],[3,6,6,7,4],[4,5,3,8,0]])
matrix_D

array([[1, 1, 1, 2, 0],
       [3, 6, 6, 7, 4],
       [4, 5, 3, 8, 0]])

In [27]:
# the different ways of indexing matrix D give different output shapes: scalar; vector; matrix
print(matrix_D[0,0].shape)
print(matrix_D[0,0:1].shape)
print(matrix_D[0:1,0:1].shape)

# the squeeze method removes all the unecessary dimensions of an array

()
(1,)
(1, 1)


In [30]:
# squeeze method returns a single numeric value which is a 0-D array rather than a scalar
matrix_D[0:1,0:1].squeeze()

array(1)

In [31]:
# this removes the unescessary dimesions associated with the matrix shape even if only returning one value
matrix_D[0:1,0:1]

array([[1]])

In [34]:
# the squeezed array of previously 1 by 1 dimension now has no shape
matrix_D[0:1,0:1].squeeze().shape

()

In [36]:
# an equivelent way of using the squeeze functions
np.squeeze(matrix_D[0:1,0:1]).shape

()

In [ ]:
# By using the squeeze method all the outputs of the different matrix are converted into equivelent outputs
print(matrix_D[0,0].squeeze().shape)
print(matrix_D[0,0:1].squeeze().shape)
print(matrix_D[0:1,0:1].squeeze().shape)