# NumPy Fundamentals

In [3]:
import numpy as np

## Indexing

In [3]:
array_a = np.array([[1,2,3],[4,5,6]])
array_a

array([[1, 2, 3],
       [4, 5, 6]])

### Specific Values

In [6]:
array_a[0] # first element of the 2d array

array([4, 5, 6])

In [7]:
array_a[1] # second element of the 2d array

array([4, 5, 6])

In [8]:
array_a[0][1] # first row and second element of first row

np.int64(2)

In [9]:
array_a[0,1] # an alternative war to get the first row and second element of first row

np.int64(2)

In [11]:
array_a[:,0] # slicing i.e. get all the rows of the first column

array([1, 4])

### Negative Indices

In [12]:
array_b = np.array([1,2,3])
array_b[-1] # get the last element of the array. It's like going backwards from 0 which is the first element to -1 which is the last element

np.int64(3)

In [13]:
array_a[-1] # for a multi-dimensional array as in this example -1 represents the last element which is the last row

array([4, 5, 6])

In [15]:
array_a[-1,-1] # get the last row and last column

np.int64(6)

## Assigning Values

In [3]:
array_a = np.array([[1,2,3],[4,5,6]])
array_a

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
# changing an element of an array
array_a[0,2] = 9
array_a

array([[1, 2, 9],
       [4, 5, 6]])

In [5]:
# changing an element of the array (but this time the entire first row)
array_a[0] = 9
array_a

array([[9, 9, 9],
       [4, 5, 6]])

In [6]:
# changing an element of the array (but this time the entire first column)
array_a[:,0] = 9
array_a

array([[9, 9, 9],
       [9, 5, 6]])

In [7]:
# changing elements of an array with list values
list_a = [8,7,8]

array_a[0] = list_a # referring to the first row of the matrix array
array_a

array([[8, 7, 8],
       [9, 5, 6]])

In [8]:
# change all the elements in the array/matrix to one value
array_a[:] = 9
array_a

array([[9, 9, 9],
       [9, 9, 9]])

In [9]:
# CAUTION: setting the matrix array to a single value overwrites the matrix structure
array_a = 9
array_a

9

## Elementwise Properties

In [5]:
array_a = np.array([7,8,9])
array_a

array([7, 8, 9])

In [6]:
array_b = np.array([[1,2,3],[4,5,6]])
array_b

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
array_a + 2 # element wise array. Adding 2 to each element in array_a

array([ 9, 10, 11])

In [8]:
array_b + 2 # element wise array (works for higher dimensional arrays). Adding 2 to each element in array_b
# element wise array works for all the other arithmetic operations

array([[3, 4, 5],
       [6, 7, 8]])

In [9]:
# element wise operations do not work for list because the purpose of list is to store data whereas the pupose of arrays is to perform calculations
# Example

list_a = [1,2,3]
list_a + [2]

[1, 2, 3, 2]

In [10]:
# adding elements from two different shaped arrays (specify the elements to make them compatible with the same shape)
array_a + array_b[0]

array([ 8, 10, 12])

In [13]:
# the shapes of the arrays need to be compatible to perform element wise e.g. the length of the 1d array should be the same 
# as the length of the 2d array

array_a * array_b

# each element in array_a multiples each element in array_b on a row by row basis

array([[ 7, 16, 27],
       [28, 40, 54]])

## Types of Data Supported by NumPy

In [16]:
array_a = np.array([[1,2,3],[4,5,6]])
array_a # default data types of arrays are set to None

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
# changing data type of nd array from the default None
array_a = np.array([[1,2,3],[4,5,6]], dtype = "float32")
array_a 

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [6]:
# alternative way of changing data type of nd array from the default None
# it is good programming practice to stay consistant with ont way
array_a = np.array([[1,2,3],[4,5,6]], np.float32)
array_a 

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [7]:
# alternative way of changing data type of nd array from the default None
array_a = np.array([[1,2,3],[4,5,6]], np.complex64) # complex data type
array_a 

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]], dtype=complex64)

In [9]:
# alternative way of changing data type of nd array from the default None
array_a = np.array([[1,0,3],[4,5,6]], np.bool) # bollean data type, anything but 0 is true
array_a

array([[ True, False,  True],
       [ True,  True,  True]])

In [12]:
# alternative way of changing data type of nd array from the default None
array_a = np.array([[1,0,3],[4,5,6]], str) # string data type (elements are enclosed in single quotes)
array_a

array([['1', '0', '3'],
       ['4', '5', '6']], dtype='<U1')

https://numpy.org/devdocs/reference/generated/numpy.dtype.kind.html <- <i> A link to the documentation explaining the unicode abbreviation.

## Characteristics of NumPy Functions

### Universal Functions

https://numpy.org/devdocs/reference/ufuncs.html <- <i> A link to the documentation page on Universal Functions

### Broadcasting

In [13]:
# vector
array_a = np.array([1,2,3])
array_a

array([1, 2, 3])

In [14]:
# vector
array_b = np.array([[1],[2]])
array_b

array([[1],
       [2]])

In [15]:
# matrix
matrix_c = np.array([[1,2,3],[4,5,6]])
matrix_c

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
# adding nd arrays of different dimensions involves the intermediate step of broadcasting i.e. converting array_b in the same shape as array_c by
# 'blowing' out array_b and adding to array_c element wise
np.add(array_b, matrix_c)

array([[2, 3, 4],
       [6, 7, 8]])

### Type Casting

In [18]:
# type casting involves taking every element of an array and changing it to a specified datatype
# type casting changes the inputs before performing the element wise operations
np.add(array_b, matrix_c, dtype = np.float64)

array([[2., 3., 4.],
       [6., 7., 8.]])

### Running over an Axis

In [19]:
np.mean(matrix_c, axis = 0) # perform the mean operation over each column in the matrix

array([2.5, 3.5, 4.5])

In [20]:
# values of the original matrix
matrix_c

array([[1, 2, 3],
       [4, 5, 6]])