# Why NumPy?

In [2]:
import numpy as np

### Ndarrays

In [3]:
array_a = np.array([1,2,3])

In [4]:
array_a

array([1, 2, 3])

In [5]:
print(array_a)

[1 2 3]


In [6]:
type(array_a)

numpy.ndarray

In [7]:
array_a.shape

(3,)

In [8]:
array_b = np.array([[7,8,9],[10,11,12]])

In [9]:
print(array_b)

[[ 7  8  9]
 [10 11 12]]


In [10]:
print(array_b.shape, ", A 2 by 3 array; 2 1-d arrays each consisting of 3 elements")

(2, 3) , A 2 by 3 array; 2 1-d arrays each consisting of 3 elements


In [11]:
array_b.shape[0] #number of rows

2

In [12]:
array_b.shape[1] #number of columns

3

In [13]:
array_c = np.array(13)

In [14]:
type(array_c) # A scalar

numpy.ndarray

In [15]:
print(array_c)

13


In [16]:
array_c.shape # a scalar has zero dimensions i.e. it is not located on a line or a plane

()

In [17]:
array_d = np.array([15]) # a point located on a line hence it has a dimension of 1 row

In [18]:
type(array_d)

numpy.ndarray

In [19]:
print(array_d)

[15]


In [20]:
array_d.shape

(1,)

### List vs Array

In [21]:
list_a = [1,2,3,4,5,6] # list

In [22]:
len(list_a)

6

In [23]:
type(list_a)

list

In [24]:
list_b = [[1,2,3],[4,5,6]] # list of lists

In [25]:
len(list_b)

2

In [26]:
array_b = np.array(list_b)

In [27]:
type(array_b)

numpy.ndarray

In [28]:
print(list_b)

[[1, 2, 3], [4, 5, 6]]


In [29]:
print(array_b)

[[1 2 3]
 [4 5 6]]


In [30]:
array_b.shape

(2, 3)

In [31]:
len(list_b) # shape function cannot be used on a list. Instead use len to get the 'shape' e.g. this list is made of 2 elements

2

In [32]:
len(list_b[0]) # this is the number of elements in the first list

3

In [33]:
list_c = list_b[0] + list_b[1] # this operation concatenates the first list with the second list
array_c = array_b[0] + array_b[1] # adds corresponding elements from the 1st and 2nd rows naturally

In [34]:
print(list_c)
print(array_c)

[1, 2, 3, 4, 5, 6]
[5 7 9]


In [35]:
# performing math functions on array can be done with another library such as math but can only be done on an element by element basis
import math
sqroot = math.sqrt(array_b[1,0])
print(sqroot)

2.0


In [37]:
# or alternatvely use the native math functions in numpy and the math operation will be performed on each element in the array
# lists don't have this element wise functionality
np.sqrt(array_b)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])